### PR TITLE
Style linting deps: use latest versions

### PR DESCRIPTION
**Pull request by adekbadek**
Updates [`wp-prettier`](https://www.npmjs.com/package/wp-prettier) to proper version, which should mitigate issues encountered in https://github.com/Automattic/newspack-theme/pull/1839. This PR also updates the code to pass the latest style linting rules. The updates were mostly done in an automated way, using the `--fix` linting option and [this migrator](https://sass-lang.com/documentation/cli/migrator).

@laurelfulford – could you have a look at the SCSS changes here?

---

Originally this work was done on [a dependabot PR](https://github.com/Automattic/newspack-theme/pull/1837), which was auto-merged after the CI issues were resolved. Since this was still experimental, I've quickly reverted the changes from master (with a force-push). In the meantime, two other dependabot PRs (`semantic-release`, `sass`) were auto-merged – my force-push undid them too, so these are added here.

### CODE REVIEW

**Comment by laurelfulford** [comment]
Thanks for this update, @adekbadek!

When running `npm run build`, I get a number of `ERROR in sass compilation Error: Undefined variable.` errors -- I think it's the change from `@import` to `@use` paired with the convoluted way the themes inherit variable values. I can dig into this a bit more today!

**Comment by laurelfulford** [comment]
Hi @adekbadek! I hope it's okay, but I went through the files and manually fixed the remaining spots where variables were 'undefined' and pushed them up to this branch -- I also rebased master against this branch to fix some conflicts, hopefully that didn't muddy things too much! 

I also made a few other changes to fix issues: 

* `@use` always outputs at the very top of the generated CSS file -- with how the theme was set up, this means the `@use` code was getting put in front of the code comments at the very top of each style.css. This is working correctly, but is messing up WordPress's ability to recognize the themes, and breaking the connection between the the child themes and the parent. As a work around, I moved the description into a separate .scss file and used `@use` to add them first -- it works, but it's a bit hacky. If it seems like an okay way to go for now, I believe the release.config.js also needs to be updated (I'm not sure that was it so I left it alone for now!). 
* I simplified the child theme variable styles, rather than splitting them into the separate fonts and colors files — this seemed a bit more straight forward than trying to override the per-theme `fonts` and `colors` in multiple different files. 

As part of my testing, I ran the compiled CSS files through a diff to compare the before and after; outside of some line break differences and some other comments moving, the only difference I noticed was in the colours in Newspack Joseph -- `#515151` switched to `#444444`. The new styles are actually correct based on the child theme's Sass, but they weren't working before. Since it's now "right" and the two colours are quite close, I've left this change -- this should be the only style difference introduced by these changes.

Lastly, though I added the namespace throughout the individual styles, another approach we could use would be to remove the namespaces when we load a style using `@use` — like  `@use '../../variables-site/colors’ as *;` . This would make it continue to work more like `@import` — for example, we could continue to do things like `color: $color__primary`, and not have to change all the styles to `color: colors.$color__primary`. I wish I had realized this before I added a bunch of the namespaces, but I wonder if this might be a better approach for the long term? 

Please let me know if you have any questions about the above, or if there's anything I should change -- thank you!

**Comment by adekbadek** [comment]
Thanks for the changes! 

> I believe the release.config.js also needs to be updated (I'm not sure that was it so I left it alone for now!).

Done in 1245c25b9cc7d1bc3d5d9b02a32f4bfc95ffbd60

> Lastly, though I added the namespace throughout the individual styles, another approach we could use would be to remove the namespaces when we load a style […] I wish I had realized this before I added a bunch of the namespaces, but I wonder if this might be a better approach for the long term?

I think namespacing is a better idea – it helps code readability and can prevent some issues.

**Comment by laurelfulford** [comment]
@adekbadek I rebased this PR against master to fix conflicts, and compared all of the files against the versions in master. Outside of the same spacing and comment changes and the changes to Newspack Joseph's colours I saw in the first pass, everything lines up and looks good to me. 

<details>
<summary><strong>CSS files reviewed</strong></summary>

**Joseph**
- [x] newspack-joseph/style.css
- [x] newspack-joseph/style-rtl.css
- [x] newspack-joseph/styles/style-editor.css
- [x] newspack-joseph/tribe-events/tribe-events.css

**Katharine**
- [x] newspack-katharine/style.css
- [x] newspack-katharine/style-rtl.css
- [x] newspack-katharine/styles/style-editor.css
- [x] newspack-katharine/tribe-events/tribe-events.css

**Nelson**
- [x] newspack-nelson/style.css
- [x] newspack-nelson/style-rtl.css
- [x] newspack-nelson/styles/style-editor.css
- [x] newspack-nelson/tribe-events/tribe-events.css

**Sacha**
- [x] newspack-sacha/style.css
- [x] newspack-sacha/style-rtl.css
- [x] newspack-sacha/styles/style-editor.css
- [x] newspack-sacha/styles/child-style-editor-overrides.css
- [x] newspack-sacha/tribe-events/tribe-events.css

**Scott**
- [x] newspack-scott/style.css
- [x] newspack-scott/style-rtl.css
- [x] newspack-scott/styles/style-editor.css
- [x] newspack-scott/tribe-events/tribe-events.css

**Default**
- [x] newspack-theme/style.css
- [x] newspack-theme/style-rtl.css
- [x] newspack-theme/styles/newspack-newsletters-editor-rtl.css
- [x] newspack-theme/styles/newspack-newsletters-editor.css
- [x] newspack-theme/styles/newspack-sponsors-editor-rtl.css
- [x] newspack-theme/styles/newspack-sponsors-editor.css
- [x] newspack-theme/styles/newspack-sponsors-rtl.css
- [x] newspack-theme/styles/newspack-sponsors.css
- [x] newspack-theme/styles/print.css
- [x] newspack-theme/styles/style-editor-customizer.css
- [x] newspack-theme/styles/style-editor-overrides.css
- [x] newspack-theme/styles/style-editor.css
- [x] newspack-theme/styles/trust-indicators-rtl.css
- [x] newspack-theme/styles/trust-indicators.css
- [x] newspack-theme/styles/woocommerce-rtl.css
- [x] newspack-theme/styles/woocommerce.css
- [x] newspack-theme/tribe-events/tribe-events.css
</details>

However, I ran into one weird issue: when I committed and pushed up the rebased SCSS and package files, I got an error for:

```
/home/circleci/project/newspack-theme/js/src/post-meta-toggles.js
  18:9  error  Replace `·newspack_hide_page_title,·newspack_hide_updated_date,·newspack_show_share_buttons·}·=⏎↹↹` with `⏎↹↹newspack_hide_page_title,⏎↹↹newspack_hide_updated_date,⏎↹↹newspack_show_share_buttons,⏎↹}·=·`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Exited with code exit status 1
```

... but the strange thing is, [this was recently changed to fix an error going the _other_ way](https://github.com/Automattic/newspack-theme/pull/1863/files).

My best guess is that this has to do with the linting changes in this PR and that formatting change getting rebased into the mix, but I wanted to confirm with you. For the short-term, I've fixed the formatting to stop the issue in this PR.

Other than this, I think this PR is good to go, but holding off "Approving" it just to make sure I'm not missing something silly with the linting!

**Comment by adekbadek** [comment]
Thank you for the diligent review!

> ... but the strange thing is, [this was recently changed to fix an error going the other way](https://github.com/Automattic/newspack-theme/pull/1863/files).

But this was changed for an earlier version of linting deps, which this PR updates. So we're good here :)

**Comment by laurelfulford** [comment]
Phew - thanks @adekbadek! 😄

**Review by laurelfulford — APPROVED** [review]
The build work well with this update, and while the CSS output is _slightly_ different, it's functionally the same as in master (it's largely formatting changes, and an unexpected fix for Newspack Joseph's colours!). 

This gets a 👍 from me!

**Pull request merged**
