### PR TITLE
Style 5: Update the navigation to make sure it's using a dark background colour

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

* Update the `mobile-sidebar`
* Update sub-menu links
* Add correct background colour to `.middle-header-contain`

### How to test the changes in this Pull Request:

1. Check out the branch and execute npm run build
2. Test the theme with style pack 5 and check the menu with and without custom colours

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by laurelfulford** [comment]
Actually, looking at it again, I have a question:

Is the solid header always meant to be black? 

Right now, it will be if you have the default colour palette, but if you change it it doesn't:

Default colours:

image

Custom colours:

image

If this is intentional, don't worry about it! 

If not, it can be added to the style packs in this  `newspack_is_active_style_pack()` function, to exclude this style pack from changing the header colour with the custom colours:

https://github.com/Automattic/newspack-theme/blob/master/inc/color-patterns.php#L343

**Comment by thomasguillot** [comment]
> Is the solid header always meant to be black?
>
> Right now, it will be if you have the default colour palette, but if you change it it doesn't

It is intentional, yes, but I'm open for feedback. Do you think it looks like a bug?

**Comment by laurelfulford** [comment]
> It is intentional, yes, but I'm open for feedback. Do you think it looks like a bug?

I think to sync it up to the other two style packs that have a neutral header colour, instead of the primary one, I would make it black all the time. But _that_ behaviour is also a bit unpredictable/bug-like, so I could just as easily argue it the other way :) 

Part of the reason I went that way was because it seemed unlikely for a site to use the default colour, and I wanted to keep the header neutral. However, those style packs use the primary colours a lot more -- I think as long as it's behaving as designed, it's fine.

**Comment by thomasguillot** [comment]
> I think to sync it up to the other two style packs that have a neutral header colour, instead of the primary one, I would make it black all the time. But that behaviour is also a bit unpredictable/bug-like, so I could just as easily argue it the other way :)
> 
> Part of the reason I went that way was because it seemed unlikely for a site to use the default colour, and I wanted to keep the header neutral. However, those style packs use the primary colours a lot more -- I think as long as it's behaving as designed, it's fine.

Yeah good point. I removed the background colour in 6a2e69e

**Pull request merged**
