### PR TITLE
feat: add Bluesky to the profile fields

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds the Bluesky profile field.

Note. There's also another filter in Yoast that I was trying, that looks like it has to do with it, but I don't see it having any effect, so I removed it. It's this:

```
add_filter(
'wpseo_person_social_profile_fields',
function( $profile_fields ) {
	if ( ! array_key_exists( 'bluesky', $profile_fields ) ) {
		$profile_fields['bluesky'] = 'get_non_valid_url';
	}
	return $profile_fields;
}
);
```

### How to test the changes in this Pull Request:

1. Edit an author profie
2. Confirm you see a new field for Bluesky profile
3. Add a url starting with https://bsky.app/profile/
4. Visit the author archive page
5. Confirm you see the Bluesky link with the correct icon

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This isn't working for me. 😕 Doing some light debugging, it looks like the `wpseo_additional_contactmethods` filter hook isn't getting called on my site. I have Yoast active and a BlueSky profile URL in my author's profile.

**Comment by leogermani** [comment]
> This isn't working for me. 😕 Doing some light debugging, it looks like the `wpseo_additional_contactmethods` filter hook isn't getting called on my site. I have Yoast active and a BlueSky profile URL in my author's profile.

If you are seeing the bluesky input in the "edit user" page it means the hook is working fine.

Have you enabled social icons for authors in the theme? It's an option in the theme somewhere. I don't know where you turn this on in the UI (probably in the Customizer), but you can also do so by `set_theme_mod( 'show_author_social', true );`

**Comment by laurelfulford** [comment]
>  I don't know where you turn this on in the UI (probably in the Customizer)

It's under Customizer > Author Bio Settings, "Display Author Social Media links" 🙂

**Review by dkoo — APPROVED** [review]
>  It's under Customizer > Author Bio Settings, "Display Author Social Media links" 🙂

Yes, that's exactly what I was missing—sorry!

**Pull request merged**
