### PR TITLE
Header: Keep centred logo from getting cut off in IE11

### LINKED ISSUE #931: Header: Centered logo cut off in IE11
Right now centered logos can be cut off in IE11, if they're wider than 1/3 of the header.

It seems to be related to all three divs in the header having `flex: 1` as a value; switching it to `flex: auto` fixes the issue, but also reintroduces the problem where the logo/site branding isn't truly centered, since the elements to the left and right aren't exactly the same width. 

The following can be used as a temp CSS fix, in cases where it doesn't cause the logo to become noticeably askew:

```
@media only screen and (min-width: 1168px) {
	.h-cl .site-header .middle-header-contain .wrapper > div {
		flex: auto;
	}
}
```

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Right now in IE11, if you centre a wider logo, it will get cut off on the right. This PR adds an IE-specific fix for that issue. Best tested after #930 lands to confirm logo scaling down still behaves as expected, as it also can cause the logo to get cut off.

Note: In my testing, most images were distorted when AMP was enabled in IE11; I filed a separate issue for that here: https://github.com/ampproject/amphtml/issues/28398

Closes #931.

### How to test the changes in this Pull Request:

1. Navigate to Customize > Header Settings > Appearance, and select Centered Logo.
2. Add a logo with a horizontal orientation, and make it rather wide -- roughly 600px wide on desktop (half the header width).
3. View in a modern browser (Firefox, Chrome, etc), and note the appearance:

image

4. View in IE11: 

image

5. Apply the PR and run `npm run build`.
6. Confirm the logo still displays at the larger size in modern browsers:

image

7. Confirm that the logo is now smaller in IE11, but no longer cut off:

image

8. Confirm that things look good in modern version of Edge.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
I'll review after https://github.com/Automattic/newspack-theme/pull/930 lands; added the `On Hold` label.

**Comment by jeffersonrabb** [comment]
Now that https://github.com/Automattic/newspack-theme/pull/930 is merged I'm getting merge conflicts, and I'm not sure how to resolve them. @laurelfulford if you could merge master into this branch I'll test right away!

**Comment by laurelfulford** [comment]
Thanks @jeffersonrabb! This PR should be up to date with master now -- too many changes happening in the same files at the same time :)

**Comment by laurelfulford** [comment]
Thanks!

**Pull request merged**
