### PR TITLE
WooCommerce: Improve checkout page appearance and simplify

### LINKED ISSUE #943: WooCommerce: Checkout flow improvements
The theme's WooCommerce styles are a bit weak; they originally focused on getting the pages a customer would see when making a donation in shape, but as publishers sell other products or memberships, we'll need to fix up the rest. 

The checkout flow needs a good review and improvements -- for example, it would be great the checkout could be customized based on purchase (like for a donation). It should also show the bare minimum -- depending on the purchase, it may not be necessary to ask for specific information, and being able to keep these pages as simple as possible depending on the customers actions would be a big improvement.

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR improves the appearance of the WooCommerce checkout page by correcting some field alignments, and removing a couple redundant fields (company, address line 2, and phone). When you only have items in your cart that don't require shipping, it strips the form down to just first and last name, and email address [Edited to add: let me know if this would make more sense as an _option_ to do, so a publication can also choose to collect billing address information, for whatever reason. I'm not sure if it would ever be necessary but it might be?].

When shipping is required, the potential shipping address is moved under the billing address, and the same field simplification (removing company, address line 2, and phone) is applied. 

**Note:** best I can tell, [this check for whether or not a product requires shipping](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L1517) checks whether or not products are virtual. It looks like the Newspack product [does create them this way](https://github.com/Automattic/newspack-plugin/blob/b82bd0a52d44c1afaf0808ba200bcdd28cda763b/includes/class-donations.php#L242), but I wanted to flag just in case we should double-check existing sites. 

Closes #943.

### How to test the changes in this Pull Request:

1. Add a digital and product that requires shipping to your cart. To test the original appearance of the shipping address, you'll need a product that has a shipping price.
2. View the Checkout page:

<details>
<summary><strong>Checkout without shipping</strong></summary>

screencapture-build-newspack-test-checkout-2021-02-27-11_52_23

</details>

<details>
<summary><strong>Checkout with shipping</strong></summary>

screencapture-build-newspack-test-checkout-2021-02-27-12_06_10

screencapture-build-newspack-test-checkout-2021-02-27-12_06_45

</details>

3. Apply the PR and run `npm run build`.
4. View the cart; note the simplified form:

<details>
<summary><strong>Checkout with shipping closed</strong></summary>

screencapture-build-newspack-test-checkout-2021-02-27-11_51_10 (1)

</details>

5. Toggle open the "Ship to a different address?" option on; confirm that the background is using the secondary colour, and that the shipping form displays well underneath it:
<details>
<summary><strong>Checkout with shipping open</strong></summary>

screencapture-build-newspack-test-checkout-2021-02-27-12_11_49

</details>

6. Remove the physical product from your cart; make sure you only have a virtual item (like a donation).
7. View the checkout page again; confirm that the form is now simplified down to the First Name, Last Name and Email address fields: 
<details>
<summary><strong>Checkout with a virtual product</strong></summary>

screencapture-build-newspack-test-checkout-2021-02-27-12_32_19

</details>

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
Instead of using the old way of checking out with WooCommerce, what if we switched this to WooCommerce Blocks?

https://developer.woocommerce.com/2020/05/27/available-for-testing-a-block-based-woocommerce-cart-and-checkout/

**Comment by laurelfulford** [comment]
> Instead of using the old way of checking out with WooCommerce, what if we switched this to WooCommerce Blocks?

Oh nice! I'll have to check them out -- that could be a really good way for publishers to customize their checkout further. I'm not sure if it would be a full either/or though -- I think it'd be nice to still support the shortcode as a backup, especially if it's not possible to conditionally load certain fields depending on what's being purchased. But having the blocks -- and even some block patterns available -- could open it up so publishers can really fine tune the fields they want to use :)

**Comment by laurelfulford** [comment]
Just to close the loop, I created a couple issues for improving the appearance of the checkout block (#1277, #1276); though we can't simplify them as much depending on the products in the cart, they look like they can be simplified a fair bit out of the box (they let you turn off fields we'd like to, like company, address line 2, and phone), and the checkout smartly does drop the shipping address when it's not needed. 

Once we make sure everything is picking up the correct colours/fonts, they'll make a nice alternative to the out of the box checkout pages.

**Review by adekbadek — APPROVED** [review]
LGTM

**Comment by adekbadek** [comment]
(merging since Laurel is AFK)

**Pull request merged**
