### PR TITLE
Removes remaining original menu cruft 🔥 

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is hopefully the final PR cleaning up unneeded menu code:

* It re-removes the `newspack_add_ellipses_to_nav()` function, something I'd previously removed but accidentally reintroduced in another PR (I had also deleted it and re-added it in that PR's history, and poorly fixed that merge conflict by re-adding it). 
* It removes `newspack_add_mobile_parent_nav_menu_items()`, a function that duplicated each 'parent' menu item, for the mobile navigation.
* It removes some code that added some markup and an SVG link to the above menu items.
* It removes the entire touch-keyboard-navigation.js. Much of this code is related to the original priority menu, and though we will need some JavaScript for the non-AMP version of the mobile menu (to toggle it open and closed on small screens, and to make sure the dropdown menus can still be used on larger tablets), it will be a near-full rewrite of what's there. It seemed easier to remove, and start fresh. 

### How to test the changes in this Pull Request:

1. Set up a primary menu with at least one dropdown.
2. On a touch device, try tapping on the `V` icon next to the menu link with a dropdown -- it should open a full-screen version of that dropdown (with some terrible styles):

Screen Shot 2019-08-05 at 3 13 02 PM

image

3. Apply the PR.
4. Make sure the menus display as expected on larger screens. 
5. On a touch device, try tapping on the `V` icon next to a menu link with a dropdown again -- it should now open the menu as a full-width dropdown:

image

(Mobile header styles are in progress so please don't worry too much about how this all looks right now!). 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by laurelfulford** [comment]
Thanks for the review, Jeff! 

> on mobile dropdown menus, there doesn't seem to be any way to dismiss once it's open?

Right! So without any JavaScript for that menu, the dropdown menu is opened/closed based on where you've focused -- it's not super clear, but you should be able to close the menu by tapping something outside of the header area (like on the content area). 

If it's okay with you, I can improve on this in a separate PR -- it will be pretty straight-forward for the non-AMP version to do with JavaScript. For the AMP version, it will take some thinking -- though this is already happening in master when using AMP, since the JavaScript that toggles that dropdown right now wouldn't be loaded.

Just let me know if you have any questions about the above!

**Comment by jeffersonrabb** [comment]
> you should be able to close the menu by tapping something outside of the header area (like on the content area)

This doesn't seem to be working for me. Tapping on content doesn't dismiss the dropdown menu, even if I go as far as to select text. So far, the only interactions I've observed that successfully dismiss the menu are:

- Clicking on other menu items (which navigate away from the current page) 
- Focusing a form element, e.g. Comment text area.

**Comment by laurelfulford** [comment]
> This doesn't seem to be working for me. Tapping on content doesn't dismiss the dropdown menu, even if I go as far as to select text. 

Thanks for double-checking that, Jeff! It is working for me on my iPhone, but to be honest, I was surprised it did; it is not working when I use the iOS simulator. 

I'm not sure it will be possible to get a non-JavaScript version of this working, but I know it's possible with JavaScript. I will have to do some digging to see what it looks like for AMP -- I'm a little worried all of the inline code could be a bit of a mess. This view of the menu would only appear on larger horizontal tablets, and at least the menus open, but it would be nice to get them closing, too. 

Are you okay with me digging into this in a separate PR?

**Comment by jeffersonrabb** [comment]
> Are you okay with me digging into this in a separate PR?

Of course! Just wanted to be sure it was captured.

**Comment by laurelfulford** [comment]
Thanks Jeff! I've added a couple points to the "header" list in #96 to cover this issue, just to be on the safe side.

**Pull request merged**
