### PR TITLE
Print styles: correct sticky header, Safari page width

### LINKED ISSUE #1936: Print styles: sticky headers and two column templates
**Describe the bug**
A couple more issues have recently come up with regards to print styles:

1. The sticky header can appear further down the page if you print the page after scrolling.
2. The two column template prints the content wider than the one column template, even though the content is the same width online.

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR further tweaks the print styles by: 
* "Unsticking" the sticky header when printing -- in some browsers, like Chrome, if you printed the page after scrolling a bit, the header would appear mid-page. 
* Swapping out the page margin approach -- `@page` isn't supported by Safari, so it was causing the right edge of the page to be cut off in some cases. 

Closes #1936

### How to test the changes in this Pull Request:

1. Set your header to sticky, and create a post and use the two column template.
2. In Chrome or Safari, scroll partway down the page, and then print/view the print preview -- the header will appear mid-page, instead of at the top (for some reason, I wasn't able to recreate this in Firefox):

image

3. In Safari, review the rest of the print preview -- note that the edge is getting cut off on the right side. This doesn't happen with the one column templates: 

image

4. Apply the PR and run `npm run build`. 
5. Repeat steps 2 and 3, and confirm that these issues are now resolved. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — APPROVED** [review]
I can submit a new issue but perhaps this can be done in this PR, since it's related to print styles:

1. RAS' "My Account" link should also be hidden:

image

2. If there's no author image, there should be no empty space (there's none in non-print styles):

image

3. Not sure if we can do anything about it, but Chrome adds these page headers and footer, which may obscure content:

image

**Comment by laurelfulford** [comment]
Thanks @adekbadek!

> RAS' "My Account" link should also be hidden

Oh, good catch! Pushed up a fix for this in [b0bd142](https://github.com/Automattic/newspack-theme/pull/1942/commits/b0bd142e78aea22d3b0633a1b8906239b19e2f44).

> If there's no author image, there should be no empty space (there's none in non-print styles)

Just to confirm for this one, is the setup that the author doesn't have an avatar set, and the Gravatar fallback is set to blank? My experience is [in that case is that there's a gap in the non-print styles as well](https://github.com/Automattic/newspack-theme/issues/1128), but I might be misunderstanding! 

> Not sure if we can do anything about it, but Chrome adds these page headers and footer, which may obscure content:

I could recreate this with and without the headers and footers -- it looks like it's related to the flex styles on `#page`, weirdly enough! I overrode those for the print styles in [a3810b2](https://github.com/Automattic/newspack-theme/pull/1942/commits/a3810b23410ed8e2b9910b6b315f2a717cdffe67), but please let me know if it's still happening for you (I tried different lengths of content, but I'm a bit paranoid that it just _seems_ fixed).

**Review by adekbadek — APPROVED** [review]
All three issues are fixed, thanks!

**Comment by laurelfulford** [comment]
Awesome -- thanks @adekbadek! 🙌

**Pull request merged**
