### PR TITLE
Update header styles 

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the header styles and markup to match the mockups. Specific changes include:

* Reworking the markup so we can add the styles in the designs (like full-width backgrounds on separate menu levels).
* Reducing spacing overall. 

This PR has a strong focus on the desktop styles; due to the complexity of the header, I'll be tackling the mobile and AMP styles and behaviour in separate PRs (the full known list of header stuff to build is in #96). 

### How to test the changes in this Pull Request:

1. Apply the PR.
2. Populate the menu areas -- the 'primary' menu is meant for more links, whereas the secondary and tertiary are meant for less, but they shouldn't be terrible if you add long menus there. 
3. Compare the appearance to the one in the Style A mockups (https://cloudup.com/ijQz_Ex1Q7w). 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
After a first pass at setting this one up, here's what I have:

Screen Shot 2019-07-10 at 6 11 02 PM

Initial questions fous on the logo size and menu styling. Does this look correct or is something misconfigured on my end?

**Comment by laurelfulford** [comment]
@jeffersonrabb thanks for the test! This looks like my missing a couple edge cases; I'm going to mark this one as needing work and make some updates.

**Comment by laurelfulford** [comment]
Ok! I've updated the header so:

* The 'primary' menu remains visually centred, with or without dropdowns (the little dropdown arrows were making this look okay for me, but it collapsed without)
* I've vertically centred the tertiary (button-like) navigation. 

I haven't constrained the logo any more, so you can still add a logo of that size; it's bigger than I mocked up but I want to leave some wiggle room. Let me know if you see any issues with that!

**Comment by jeffersonrabb** [comment]
Here are a couple of menu layout odds and ends. I've reduce Primary menu items to three so my test environment is more reasonable than it was prior:

- At pretty moderate widths (<~850px) the primary menu stacks and there's no vertical space between the rows:
Screen Shot 2019-07-11 at 12 32 43 PM

- At mobile widths the primary nav renders under the logo (which I assume is correct) but doesn't left align with the logo. You noted in the description that the focus of this PR is desktop, so if this comment is better considered in another one, feel free to ignore...
Screen Shot 2019-07-11 at 12 32 52 PM

**Comment by laurelfulford** [comment]
Thanks @jeffersonrabb! 

I think both of those are worth fixing in this PR. There's a lot more hairy stuff on mobile that I didn't want to get into with this one, because it could get pretty epic, but basic stacking is pretty straight-forward :)

**Comment by laurelfulford** [comment]
I made some minor adjusting to the spacing so the header breaks down nicer on smaller screens.

**Before:** 
Screen Shot 2019-07-11 at 10 15 17 AM
Screen Shot 2019-07-11 at 10 16 40 AM
Screen Shot 2019-07-11 at 10 16 48 AM

**After:** 
Screen Shot 2019-07-11 at 10 17 15 AM
Screen Shot 2019-07-11 at 10 21 23 AM
image

The only thing still standing out to me is the vertical alignment on the 'more' link in the priority menu on mobile. But since that won't work with AMP -- it requires JavaScript -- I think it makes sense to remove it.

**Pull request merged**
