### PR TITLE
Add custom style to subscribe patterns

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds specific custom styles to some new patterns I added to Newspack Blocks (https://github.com/Automattic/newspack-blocks/pull/1091).

__Note: These patterns are meant for an Overlay and not an Inline so I didn't add specific CSS for Inline (will do in a separate PR)__

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Create an Overlay Prompt
3. Insert Pattern > Subscribe 7/8/9
4. Preview

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
I have an issue with lint... when I run `npm run format:scss` I get `prettier: command not found`

**Comment by laurelfulford** [comment]
@thomasguillot I can't recreate the issue with lint; it works for me, but also at times I feel like those kinds of things only work on my computer based on luck and which direction the wind is blowing 😐 

Let me know if it would help if I ran `npm run format:scss` locally on this PR and pushed up any changes!

**Comment by thomasguillot** [comment]
Managed to fix the `lint` issue (https://github.com/Automattic/newspack-theme/pull/1760/commits/0eec23e5ad7eaefe719aeea860e7b9f88e0638c7). I had to reinstall prettier for some reason `npm i prettier` 🤔

**Review by laurelfulford — APPROVED** [review]
All of these new styles (and patterns!) look good! 🚢 

I tested with a variety of overlay placements and sizes, at different breakpoints. While there were some understandable clashes (#7 and 'small' campaign sizes, for example, don't mix), they previewed accurately in the editor, which should guide people to make good decisions about the options like this that they can change.

**Pull request merged**
