### PR TITLE
Post Carousel: Adjust styles when used in certain widget areas

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adjusts the font sizing, padding and navigation size of the post carousel controls when it's used in the narrower widget spaces (sidebar, slide out sidebar, and in the mobile menu).

It also updates how we prevent the hidden fallback slide out menus from being tabbed into (`visibility: hidden` when they were originally `display: none`) -- this makes sure the hidden post carousel actually gets initialized when AMP is disabled. 

See #1372.

Note: this should be tested after #1407 because it kind of relies on the font size and link spacing fixes from that PR. 

### How to test the changes in this Pull Request:

1. Add the post carousel block to the sidebar and slide-out sidebar widget areas, and set the slide-out sidebar widgets to display in the mobile menu.
2. View on the front-end; note how the carousel is somewhat crowded, and the controls can overlap the text:

image

3. Apply the PR and run `npm run build`.
4. Confirm that the spacing is improved:

image

5. Disable AMP.
6. Confirm that the post carousel still works in the hidden widget areas. 
7. Try to tab through the page and confirm that, when the slide-out sidebar isn't open, you can't accidentally tab into the links there. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This fixes mostly everything. The only thing I see is a small bit of top/left margin and padding on the `a` elements when in the slide-out sidebars:

Screen Shot 2021-07-13 at 1 13 34 PM

**Comment by laurelfulford** [comment]
Thanks @dkoo! I think the issue is that I didn't update this PR to include the fixes from #1407, which made the link styles more specific so they don't add spacing on every `<a>` in that section. 

I've updated this PR so it should include everything currently in master -- can you please try again and see if that fixes it for you? It should, based on my testing 🤞  Thanks!

**Review by dkoo — APPROVED** [review]
Yep, that seems to have fixed it!

**Comment by laurelfulford** [comment]
Yay! Thanks for double-checking!

**Pull request merged**
