### PR TITLE
Featured Image: Add above placement to single posts

### LINKED ISSUE #1089: Featured Image: Add option for placement 'above'
We've had a couple requests now to kind of mash up the 'behind' featured image style, and the large image -- in both cases, it was an ask to have a full-width featured image at the top of a post (exact same placement as the featured image behind), but the title below it -- similar to: 

https://www.papermag.com/wales-bonner-spring-2021-film-2647846893.html

We could either have an image at 100% of its width without cropping (letting the height fall where it may), or do a similar cover image treatment as the featured image behind (with the downside being that the image could get cropped a bit).

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds an option to place the featured image above the post title, as both a site-wide and per-post setting.

**Note:** This PR needs #1123 to land before needing review, so the same option can be added for pages. 

Closes #1089

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build`.
2. Navigate to Customizer > Template Settings > Post Settings and confirm there is now a global option to set the featured image 'Above article title'.
3. Change the setting and confirm it's applied to posts without specific featured image placements. The image should display at full width and uncropped, with the caption underneath if available:

image

4. Undo the above; change the setting on an individual post and confirm it's applied to that specific post.
5. Test on different screen sizes to make sure it looks good:

image

6. Repeat the above steps with the global page option under Customizer > Template Settings > Page Settings, and on a single page.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — CHANGES_REQUESTED** [review]
I'm having trouble testing this – looks like the new placement is disregarded. When I set the "Featured Image Default Position" to "Above article title" no change is visible on the frontend, and after reloading the customizer the setting is back to "Large". This also happens after I merge the `master` in locally.

**Comment by laurelfulford** [comment]
Thanks Adam! Looks like it was a silly mistake on my part -- the new setting wasn't included in the sanitation options for the featured image, so it wasn't saving from there 🤦‍♀️ it should be working as expected now!

**Review by adekbadek — APPROVED** [review]
👌

**Comment by laurelfulford** [comment]
Thanks! 🙌

**Comment by laurelfulford** [comment]
Documentation added here: https://newspack.pub/support/themes/featured-images/#above

**Pull request merged**
