### PR TITLE
fix: update custom font selectors in the editor styles

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

With WordPress 5.7, some of the markup in the editor changed, making it so some custom fonts were no longer applied. 

This PR adds updated selectors, but doesn't override the existing ones, in case the markup of existing blocks wouldn't have changed. 

### How to test the changes in this Pull Request:

1. Start with the default theme, and set up some obvious custom fonts.
2 Set up a post with a variety of blocks that use the header font, or copy [this test content](https://cloudup.com/cmduE5VnrN5) -- it includes a number of the blocks that use header fonts, including header, pullquotes (in some cases), some of the widget blocks, and tables.
3. Publish.
4. Note that some elements in the header - like the title and header blocks aren't picking up the header fonts, when compared to the front end.
5. Apply the PR and confirm that the fonts are now corrected. 
6. Cycle through the different child themes and confirm things are working as expected, compared to the front-end -- the main thing that can change from theme to theme is the dropcap, and pullquote block -- some themes use the body font, and others the header font.

<details>
<summary><strong>Default theme</strong></summary>

<strong>Default theme - before:</strong>

image

image

<strong>Default theme - after</strong>

image

image
</details>

<details>
<summary><strong>Newspack Joseph</strong></summary>

<strong>Newspack Joseph - before:</strong>

image

image

<strong>Newspack Joseph - after</strong>

image

image

</details>

<details>
<summary><strong>Newspack Katharine</strong></summary>

<strong>Newspack Katharine - before:</strong>

image

image

<strong>Newspack Katharine - after</strong>

image

image

</details>

<details>
<summary><strong>Newspack Nelson</strong></summary>

_Note: I've switched the custom header font to Georgia for these screenshots, since the original one I was testing with, Raleway, is pretty close to this theme's default._

<strong>Newspack Nelson - before:</strong>

image

image

<strong>Newspack Nelson - after</strong>

image

image

</details>

<details>
<summary><strong>Newspack Sacha</strong></summary>

<strong>Newspack Sacha - before:</strong>

image

image

<strong>Newspack Sacha - after</strong>

image

image

</details>

<details>
<summary><strong>Newspack Scott</strong></summary>

<strong>Newspack Scott - before:</strong>

image

image

<strong>Newspack Scott - after</strong>

image

image

</details>

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This works great for the most part. I used your test content and set a serif for headings and a sans-serif for body type to test. 

I did see a few minor things that look off (maybe unrelated to the changes? If so, let me know if anything is out of scope). Details below:

### All themes

The Latest Comments block breaks out of the column in the editor:

Screen Shot 2021-03-10 at 5 57 11 PM

The Archives block has some side padding in the editor that doesn't exist on the front-end. Also note the difference in visited link color: the visited links are black on the front-end but not in the editor (this seems to be the case for all links, not just this block—not sure if it's a problem so noting just in case). Editor:

Screen Shot 2021-03-10 at 5 58 26 PM

Front-end:

Screen Shot 2021-03-10 at 5 58 31 PM


### Joseph

In the editor, the first Pullquote block shows the body type for the attribution:

Screen Shot 2021-03-10 at 5 52 52 PM

On the front-end, the attribution is in the heading type:

Screen Shot 2021-03-10 at 5 52 56 PM

Some minor color discrepancy in the File block in editor vs. front-end:

Screen Shot 2021-03-10 at 6 00 17 PM
Screen Shot 2021-03-10 at 6 00 21 PM

### Sacha

The Quote block has italics in the editor, but not the front-end:

Screen Shot 2021-03-10 at 6 05 43 PM
Screen Shot 2021-03-10 at 6 05 38 PM

**Comment by laurelfulford** [comment]
Thanks Derrick!

There are a few things here that are old issues (comments, archives, categories...) but they were such low hanging fruit, it seemed silly to leave them -- I've added some fixes so the spacing on these blocks should be less wacky.

The file button colour issue should be fixed, but I've left the visited link part -- I don't think that's new, and I'm a little worried about starting to pull that thread right now 😬 

The Pullquote issues should be fixed in Newspack Joseph and Sacha; I also updated the font styles on Newspack Joseph for both the front end and the editor so the File block matches the button block -- that's how it is in all of the other themes, and seemed odd that it was different in this one.

Please let me know if you have any questions about the above, or if anything still looks off!

**Review by dkoo — APPROVED** [review]
Thanks for the fixes—the comment block thing in particular was bothering me 😆 

I do still see a discrepancy in the color of the File block button in Joseph: it's dark grey in the editor but black on the front-end. But it's such a small discrepancy for a block that's probably not often used, so I'm going to approve anyway.

**Comment by laurelfulford** [comment]
Thanks Derrick! 

> I do still see a discrepancy in the color of the File block button in Joseph: it's dark grey in the editor but black on the front-end. But it's such a small discrepancy for a block that's probably not often used, so I'm going to approve anyway.

Dang it, it's like whack a mole! I've [made a new issue](https://github.com/Automattic/newspack-theme/issues/1300) for auditing the fonts and colours code in the editor.  I guarantee there are more little issues like that, and I'd like to simplify the styles used for the custom fonts and colours, so they're less likely to break in future releases.

**Pull request merged**
