### PR TITLE
Fix: Update screenshots for Newspack Nelson, Joseph, to correct logo

### LINKED ISSUE #716: Screenshot: Wrong Newspack logo for Nelson and Joseph
**Describe the bug**
Nelson and Joseph are using the wrong Newspack logo for their screenshot.

**To Reproduce**
1. Go to Appearance > Themes
2. See error

**Screenshot**
Screenshot 2020-01-21 at 10 40 56

**Expected behavior**
It should be the same Newspack logo as the other child themes

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This change updates the screenshots for Newspack Nelson and Joseph, to correct the out of date Newspack logo used.

I also ran them both through TinyPNG and will do the rest of the themes, to make the file size less huge. 

Closes #716.

### How to test the changes in this Pull Request:

1. Apply PR.
2. Review screenshots for the two themes; confirm that they're now using the version with the 'corrected' N (for lack of a better way to put it!), like on https://newspack.blog/.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by laurelfulford** [comment]
> Just confirming the Newspack icons are supposed to be white on black in these screenshots, correct?

I knocked the background out of the one on Newspack Nelson, so the icon itself is the same colour as the background, so it didn't stick out too much:

image

I'm not sure we have any guidelines around that kind of stuff yet, though, and whether if I did is OK 😬 @thomasguillot, could you weigh in on this, and confirm whether the N should always be white? Thanks!

**Comment by thomasguillot** [comment]
> @thomasguillot, could you weigh in on this, and confirm whether the N should always be white? Thanks!

It should be the same color as the background.

Screenshot 2020-01-22 at 17 34 04

So we're all good.

**Comment by laurelfulford** [comment]
> It's still the old logo for Joseph

I swear I switched both, I'm not sure how I managed this -- _especially_ since it was the same logo file. 🤦‍♀ I suspect compressing the files didn't help, since it hid the fact the file was the same. 

Joseph should be correct in 1ce9358!

**Comment by laurelfulford** [comment]
Thanks for catching that, Thomas!

**Pull request merged**
