### PR TITLE
feat: add option to set footer logo size

### LINKED ISSUE #1218: Footer Logo: Add logo sizer for the footer logo
Right now, the site logo will be displayed in the footer, and there's an option to upload a second version of the logo for there, in case it needs to contrast against a different colour.

Unlike the header logo, the footer logo always displays at one fixed maximum width and height, which doesn't always work with all logo shapes. It would be helpful to have a similar resizing slider for this logo, that would change the logo size there independent of the header, regardless if it uses the same logo file as the header, or its own file.

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds an option to switch the footer logo to use a larger size.

Note: The footer logo currently only displays if you have footer widgets assigned. This is probably something we want to untangle separately, to make the design wizard less confusing. 

Closes #1218

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build`.
2. If you haven't already, navigate to Cusotmizer > Widgets > Footer and add at least one footer widget.
3. Navigate to Customizer > Site Identity, and confirm that you have a dropdown underneath the Footer logo setting, that defaults to 'Small':

image

4. Try changing the logo size to large -- this should change the logo max width and height from 200px x 75px, to 350px x 150px on screen sizes larger than tablet. 
5. Confirm that your logo is now sized up:

**Small:**

image

**Large:**

image

6. If you have a Footer Logo file assigned, unassign it so it falls back to the main logo. (If you don't, assign a Footer Logo, so you can test the opposite of what you've already tested).
7. Test both the Small and Large footer logo sizes, and confirm they still work. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
Works well. I added 2 more sizes in https://github.com/Automattic/newspack-theme/pull/1302/commits/81589f5de1e6da35bb956b83235db0fc7dbf0d4a

I've also changed the sizes a bit, to follow a 8px baseline. This means that the default size is now 76px instead of 75px. I'm pretty certain no one will notice 😅

**Review by dkoo — CHANGES_REQUESTED** [review]
The image display is working well, but I have one request: is it possible to skip the crop step (or allow skipping it) when selecting a footer image? It seems there's no way to select an existing image without cropping it first, and even if I set the crop boundaries to the full image, it creates a duplicate of the selected image.

Also, when cropping I frequently ran into the following error. Not sure if it's related to anything codewise or if it's just my local environment, though:

Screen Shot 2021-03-16 at 10 43 37 AM

**Comment by thomasguillot** [comment]
@dkoo done in https://github.com/Automattic/newspack-theme/pull/1302/commits/299e84fcb47952048bc6bb18c3f8938bcd6b5fd1

Note: It should affect current sites because `newspack-footer-logo` has already been generated and it would require to use something like [Regenerate Thumbnail](https://wordpress.org/plugins/regenerate-thumbnails/) to resize old images.

If you upload a new image (and/or use Regenerate Thumbnail to get the correct size) then the skip cropping should work 😊

**Review by dkoo — APPROVED** [review]
Exactly what I wanted, thanks! Question, though:

> If you upload a new image (and/or use Regenerate Thumbnail to get the correct size) then the skip cropping should work 😊

Does this mean if an existing site sets the footer image to a previously existing image (before the new image size) AND skips cropping, it'll show the full-size image there? That's not really a bug IMO, but maybe something we should let publishers know about when rolling out the new feature.

**Comment by thomasguillot** [comment]
> Does this mean if an existing site sets the footer image to a previously existing image (before the new image size) AND skips cropping, it'll show the full-size image there? That's not really a bug IMO, but maybe something we should let publishers know about when rolling out the new feature.

If they don't run  Regenerate Thumbnail, then no, the existing image will have the previously forced ratio.
If they upload a new image, it will be fine.

Tbh, it sounds like an edge case that would be easily fixed by the publication/TAM.

**Pull request merged**
