### PR TITLE
perf: disable lazy load for featured images

### LINKED ISSUE #1605: Performance: avoid lazy loading featured images
**Is your feature request related to a problem? Please describe.**
https://github.com/Automattic/newspack-blocks/issues/969 describes some possible optimizations we could implement to improve the [LCP](https://web.dev/lcp/) metric of Core Web Vitals. These optimizations could also apply to above-the-fold images rendered by theme templates, especially in archive and singular article pages.

Use the [Web Vitals tool](https://web.dev/measure/) to measure performance impact before and after these optimizations.

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR disables lazy loading for every first featured image to be displayed on a page in order to improve Largest Contentful Paint (LCP) score.

Also adds the `data-hero-candidate` attribute to take advantage of AMP's prerendering features for LCP improvement.

Closes #1605.

### How to test the changes in this Pull Request:

With AMP Plus on:

1. With a site on JN or behind ngrok, while on the master branch, visit a single post with the featured image positioned to "behind article title".
2. Visit the post and observe the featured image `` tag with `loading="lazy"` attribute.
3. Run this URL on https://web.dev/measure and observe the red flag "Largest Contentful Paint image was lazily loaded"
4. Switch to this branch
5. Refresh the page and see the `` tag no longer has the attribute
6. Run the URL on https://web.dev/measure again, with an extra `?v=2` for caching purposes
7. Observe the lazy load flag is gone

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This works as described and suppresses the LCP warning. However, I think it's a bit too aggressive—it also ends up removing lazy loading and adding the `data-hero-candidate` attribute for all image thumbnails on archive pages. I think we'd want to at most apply these changes to the first image on any archive page, only.

**Comment by miguelpeixe** [comment]
I agree! I was thinking of implementing an extra parameter for the template function but I realized that there's no other case of disabling the lazy load if not the first featured image to be displayed. 

f4e1d8b7fe1c41a9a5a27054545df73c0de5cc1a implements the use of a global variable to identify if we are passed the first image and determine the arguments from there.

**Comment by laurelfulford** [comment]
> Also adds the `data-hero-candidate` attribute to take advantage of AMP's prerendering features for LCP improvement.

Just to add some more context/information, AMP _will_ add the `data-hero-candidate` and  `data-hero` attributes automatically in newer versions of the AMP plugin (in versions 2.1.3 and 2.1.4). If you're using the theme's master branch and a newer version of the AMP plugin, the following CSS will show which images are getting the attribute -- it's usually the logo, and first featured image: 

```
img[data-hero-candidate] {
	border: 4px solid red;
}
```

image
 
This isn't much help for any sites running an older version of the plugin, though! In an previous theme issue for this, [I'd suggested leaving this attribute to the plugin](https://github.com/Automattic/newspack-theme/issues/1502), but that was a few months ago. At this point, it could make sense to add it as a backup to the theme and blocks, but it could be removed again once we can get all sites on the latest version of AMP!

**Review by dkoo — APPROVED** [review]
Thanks for the update—looks good, now! Hopefully this helps with CWV performance ratings a little bit.

**Comment by miguelpeixe** [comment]
Thanks, @dkoo!

Thank you for the context @laurelfulford! I think that by using this method we can ensure that the first featured image displayed is a hero candidate. It's not a problem if it's checked twice and doesn't hurt for non-AMP cases either. What do you think?

**Comment by dkoo** [comment]
@laurelfulford Thanks for that extra context—I didn't realize AMP was already adding the `data-hero-candidate` attribute. But I agree with @miguelpeixe on this:

> I think that by using this method we can ensure that the first featured image displayed is a hero candidate. It's not a problem if it's checked twice and doesn't hurt for non-AMP cases either. What do you think?

By including it in our template code, we can ensure that the attribute is always present on the featured images we want, even if not running a more recent version of AMP.

**Comment by yogeshbeniwal** [comment]
This is a nice performance enhancement. Surprisingly page Title is detected as Largest Contentful Paint element (LCP) both on Desktop and Mobile, section#primary > main#main > header.entry-header > h1.entry-title.

**Comment by laurelfulford** [comment]
> I think that by using this method we can ensure that the first featured image displayed is a hero candidate. It's not a problem if it's checked twice and doesn't hurt for non-AMP cases either. What do you think?

@miguelpeixe That sounds good to me! 👍

**Pull request merged**
