### PR TITLE
fix: update prettier settings to remove deprecated check

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates a deprecated linting function, replacing `jsxBracketSameLine` with `bracketSameLine`. This is to resolve some linting errors thrown by CircleCI being thrown for PRs as of https://github.com/Automattic/newspack-theme/pull/1836.

### How to test the changes in this Pull Request:

1. Run `npm run lint` in the theme directory. 
2. Note the following errors:

```
jsxBracketSameLine is deprecated.
```

and

```
...wp-content/themes/newspack-theme/js/src/post-meta-toggles.js
  18:9  error  Replace `⏎↹↹newspack_hide_page_title,⏎↹↹newspack_hide_updated_date,⏎↹↹newspack_show_share_buttons,⏎↹}·=·` with `·newspack_hide_page_title,·newspack_hide_updated_date,·newspack_show_share_buttons·}·=⏎↹↹`  prettier/prettier`.
```

3. Apply the PR. 
4. Confirm that `npm run lint` no longer returns errors. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
I'm not seeing the `jsxBracketSameLine` on either master or this branch (`npm run lint` passes for me).

Are the changes to `package-lock.json` necessary, since there aren't any changes to `package.json`?

**Comment by laurelfulford** [comment]
> I'm not seeing the jsxBracketSameLine on either master or this branch (npm run lint passes for me).

I think I jumped to conclusions here 😕 I wasn't getting it when I ran `npm run lint` but I assumed my environment might be out of date because a [bunch of the latest "bump" PRs are failing that specific test](https://app.circleci.com/pipelines/github/Automattic/newspack-theme/2141/workflows/b85b6ae7-afa9-48f4-9ef7-eda7a740a1cc/jobs/4046) (though no other PRs are). Would this be something specific to how we handle the PRs that keep everything up to date that would make them get different results like this? 

> Are the changes to package-lock.json necessary, since there aren't any changes to package.json?

🤦‍♀️ No, not at all -- rolling that piece back!

**Review by dkoo — APPROVED** [review]
> a [bunch of the latest "bump" PRs are failing that specific test](https://app.circleci.com/pipelines/github/Automattic/newspack-theme/2141/workflows/b85b6ae7-afa9-48f4-9ef7-eda7a740a1cc/jobs/4046) (though no other PRs are). Would this be something specific to how we handle the PRs that keep everything up to date that would make them get different results like this?

That's strange! I'm not aware of anything in the dependabot PRs that should trigger different linting results. I see that the lint job is passing on this branch now, so let's merge and see if it fixes the problem 🤞

**Comment by laurelfulford** [comment]
Thanks @dkoo! Crossing my fingers, too... 🤞

**Comment by laurelfulford** [comment]
🚫 🎲 😞

**Comment by adekbadek** [comment]
The issue here was that after the dependency updates, `prettier` was resolved to the latest version, which overwrote the WP-formatting version ([`wp-prettier`](https://www.npmjs.com/package/wp-prettier)). https://github.com/Automattic/newspack-theme/pull/1845 should resolve these issues.

**Pull request merged**
