### PR TITLE
feat: redesign "My Account" page

### LINKED ISSUE #1878: Improve UI for WC's "My Account" page
The current UI does not provide a good UX for navigating the account inner pages:

image

The page navigation should occur with 2 columns for improved experience, when registered with a one-column template:

image

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Implements a column style for WC's "My Account" page on desktop.

image

The link background color should be updated to use the `primary` global variable, which is being tackled at #1875 

Closes #1878 

### How to test the changes in this Pull Request:

1. Make sure your "My Account" page uses the "One column" template
2. Visit WC's "My Account" page while logged out
3. Confirm the login page style is unaltered
4. Authenticate and confirm the new UI
5. Change your viewport to mobile (< 768) and confirm the navigation is responsive

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
@miguelpeixe I've updated a few things and added support for custom colours. Let me know if it works.

**Comment by miguelpeixe** [comment]
👌 love it!

**Review by adekbadek — APPROVED** [review]
Works as described.
What does the `composer.json` change do?

**Comment by thomasguillot** [comment]
> What does the composer.json change do?

@adekbadek I'm not quite sure. I wasn't able to commit my changes without this.
I've had some weird issues with composer and my php version lately (only with `newspack-theme`)

**Pull request merged**
